### ISSUE TITLE
Improve contrast of interactive example

### ISSUE THREAD

**Issue by schalkneethling** [mdn/interactive-examples#2054]
There are probably other situations where too little contrast makes things hard to see. Compare these white letters on bright yellow background atop this page,

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

I'll stop reporting these, anyone could find them easily.

_Originally posted by @iDave2 in https://github.com/mdn/yari/issues/5387#issuecomment-1055782535_

**Comment by vedant-z** [comment]
![Uploading r4{bfc025b} (290f7d3c-25a8-48b2-b308-0d7245079b1a id=0x7f0a0400 tag=BaseCommentFragment) …]()

@schalkneethling Are you referring to this part. If so I need to change the BG color for better visibility right?

**Comment by bsmth** [comment]
Has this already been fixed in the following PR?

- [x] https://github.com/mdn/css-examples/pull/75

**Comment by NiedziolkaMichal** [comment]
Unfortunately there are still plenty of examples with too low contrast.

**Comment by vedant-z** [comment]
@NiedziolkaMichal Can you point out me some so that I can get started contributing to this repository

**Comment by NiedziolkaMichal** [comment]
Those are all CSS examples that don't meet proper contrast guidelines in dark theme according to the firefox accessibility tool:
- [x] [all](https://developer.mozilla.org/en-US/docs/Web/CSS/all) #2460
- [x] [backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) #2460
- [x] [backface-visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/backface-visibility) #2460
- [x] [background-attachment](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment) #2460
- [x] [background-clip](https://developer.mozilla.org/en-US/docs/Web/CSS/background-clip) #2460
- [x] [background-origin](https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin) #2460
- [x] [bottom](https://developer.mozilla.org/en-US/docs/Web/CSS/bottom) #2419
- [x] [box-decoration-break](https://developer.mozilla.org/en-US/docs/Web/CSS/box-decoration-break) #2460
- [x] [box-sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing) #2460
- [x] [clear](https://developer.mozilla.org/en-US/docs/Web/CSS/clear) #2460
- [x] [color](https://developer.mozilla.org/en-US/docs/Web/CSS/color) #2460
- [x] [counter-set](https://developer.mozilla.org/en-US/docs/Web/CSS/counter-set) #2473
- [x] [float](https://developer.mozilla.org/en-US/docs/Web/CSS/float) #2473
- [x] [inset-block-end](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block-end) #2473
- [x] [inset-block-start](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block-start) #2473
- [x] [inset-block](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-block) #2473
- [x] [inset-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline-end) #2473
- [x] [inset-inline-start](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline-start) #2473
- [x] [inset-inline](https://developer.mozilla.org/en-US/docs/Web/CSS/inset-inline) #2473
- [x] [inset](https://developer.mozilla.org/en-US/docs/Web/CSS/inset) #2473
- [x] [left](https://developer.mozilla.org/en-US/docs/Web/CSS/left) #2419
- [x] [list-style-type](https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type) #2469
- [x] [margin-block-end](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block-end) #2469
- [x] [margin-block-start](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block-start) #2469
- [x] [margin-block](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-block) #2469
- [x] [margin-bottom](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-bottom) #2469
- [x] [margin-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-end) #2469
- [x] [margin-inline-start](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start) #2469
- [x] [margin-inline](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline) #2469
- [x] [opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity) #2489
- [x] [pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) #2469
- [x] [right](https://developer.mozilla.org/en-US/docs/Web/CSS/right) #2419
- [x] [scroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) #2475
- [x] [text-emphasis-position](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis-position) #2452
- [x] [text-emphasis](https://developer.mozilla.org/en-US/docs/Web/CSS/text-emphasis) #2475
- [x] [top](https://developer.mozilla.org/en-US/docs/Web/CSS/top) #2419
- [x] [transform-origin](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-origin) #2419
- [x] [transform-style](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-style) #2452 
- [x] [angle](https://developer.mozilla.org/en-US/docs/Web/CSS/angle) #2437

**Comment by wbamberg** [comment]
This has again been reported at https://github.com/mdn/interactive-examples/issues/2368. It's sad that such a bad usability issue has been open for so long :(

See also https://github.com/mdn/bob/issues/859.

**Comment by Maykon153** [comment]
Olha já estou ciente de TD que está acontecendo em já vem acontecendo a anos atrás vcs tem propriedades que eu tenho direito e nunca recebi nada vc sabe TDS minhas informações entre em contato comigo e passe um volor financeiro pra eu ter uma vida estável e só isso quero

**Comment by Maykon153** [comment]
Não vou abrir nenhum tipo de link que aparecer pra min

**Comment by bsmth** [comment]
For the editor styles, this has been largely fixed in https://github.com/mdn/bob/pull/888
For the individual examples, there's been a significant amount of work done to update the contents for improvements, such as https://github.com/mdn/interactive-examples/issues/2054#issuecomment-1331308570. I think it's better to close as completed for now and we can track any other bugs in the content repo when we see them. See https://github.com/mdn/rari/pull/84 and https://github.com/orgs/mdn/discussions/782 for more information. Thanks, everyone! 🎉
