### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/interactive-examples#2374]
**Missing HTML examples**
- [ ] [for](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/for) #2376 
- [ ] [crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) https://github.com/mdn/interactive-examples/pull/2314
- [ ] [is](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/is) https://github.com/mdn/interactive-examples/pull/2234
- [ ] [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) https://github.com/mdn/interactive-examples/pull/2226
- [ ] [slot element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot) https://github.com/mdn/interactive-examples/pull/2177
- [ ] [slot attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot) https://github.com/mdn/interactive-examples/pull/2177
- [ ] [part](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/part) https://github.com/mdn/interactive-examples/pull/2177
- [ ] [exportparts](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/exportparts) https://github.com/mdn/interactive-examples/pull/2224
- [ ] [draggable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable) https://github.com/mdn/interactive-examples/pull/2220
- [ ] [template](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) https://github.com/mdn/interactive-examples/pull/2219
- [ ] [output](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output) https://github.com/mdn/interactive-examples/pull/2214
- [ ] [dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) https://github.com/mdn/interactive-examples/pull/2212

**Missing CSS examples**
- [ ] [contain-intrinsic-size](https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-size)
- [ ] [contain-intrinsic-width](https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-width)
- [ ] [contain-intrinsic-height](https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-height)
- [ ] [contain-intrinsic-block-size](https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-block-size)
- [ ] [contain-intrinsic-inline-size](https://developer.mozilla.org/en-US/docs/Web/CSS/contain-intrinsic-inline-size)
- [ ] [content-visibility](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility)
- [ ] [@container](https://developer.mozilla.org/en-US/docs/Web/CSS/@container) #2481
- [ ] [container-name](https://developer.mozilla.org/en-US/docs/Web/CSS/container-name)
- [ ] [container-type](https://developer.mozilla.org/en-US/docs/Web/CSS/container-type)
- [ ] [container](https://developer.mozilla.org/en-US/docs/Web/CSS/container)
- [ ] [overscroll-behavior-block](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-block)
- [ ] [overscroll-behavior-inline](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-inline)
- [x] [overscroll-behavior-x](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-x) #2442 
- [x] [overscroll-behavior-y](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y) #2448 
- [ ] [scrollbar-gutter](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) https://github.com/mdn/interactive-examples/pull/2427
- [ ] [clip](https://developer.mozilla.org/en-US/docs/Web/CSS/clip)
- [ ] [overflow-clip-margin](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-clip-margin) #2474
- [ ] [overflow-x](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x)
- [ ] [overflow-y](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-y)
- [ ] [-webkit-line-clamp](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp)
- [ ] [-webkit-text-fill-color](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-fill-color)
- [ ] [-webkit-text-stroke](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke) #2449
- [ ] [-webkit-text-stroke-color](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke-color) #2449
- [ ] [-webkit-text-stroke-width](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-stroke-width) #2449
- [ ] [font-palette](https://developer.mozilla.org/en-US/docs/Web/CSS/font-palette)
- [ ] [@font-palette-values](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-palette-values)
- [ ] [page](https://developer.mozilla.org/en-US/docs/Web/CSS/page)
- [ ] [touch-action](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) https://github.com/mdn/interactive-examples/pull/2302
- [ ] [:modal](https://developer.mozilla.org/en-US/docs/Web/CSS/:modal) https://github.com/mdn/interactive-examples/pull/2316
- [ ] [:indeterminate](https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate) https://github.com/mdn/interactive-examples/pull/2199
- [ ] [:defined](https://developer.mozilla.org/en-US/docs/Web/CSS/:defined) https://github.com/mdn/interactive-examples/pull/2199
- [ ] [:fullscreen](https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen) https://github.com/mdn/interactive-examples/pull/2196
- [ ] [:scope](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope) https://github.com/mdn/interactive-examples/pull/2196
- [ ] [:root](https://developer.mozilla.org/en-US/docs/Web/CSS/:root) https://github.com/mdn/interactive-examples/pull/2186
- [ ] [:host](https://developer.mozilla.org/en-US/docs/Web/CSS/:host) https://github.com/mdn/interactive-examples/pull/2186
- [ ] [:host()](https://developer.mozilla.org/en-US/docs/Web/CSS/:host_function) https://github.com/mdn/interactive-examples/pull/2186
- [ ] [::slotted](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted) https://github.com/mdn/interactive-examples/pull/2177
- [ ] [::part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) https://github.com/mdn/interactive-examples/pull/2177
- [ ] [::backdrop](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop) https://github.com/mdn/interactive-examples/pull/2175
- [ ] [@keyframes](https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes) https://github.com/mdn/interactive-examples/pull/2094
- [ ] [@counter-style](https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style) https://github.com/mdn/interactive-examples/pull/2089
- [ ] [@page](https://developer.mozilla.org/en-US/docs/Web/CSS/@page) https://github.com/mdn/interactive-examples/pull/2216

**Missing JavaScript examples**
- [ ] [notify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/notify)
- [ ] [wait](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/wait)
- [ ] [waitAsync](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics/waitAsync)
- [ ] [BigInt64Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt64Array/BigInt64Array)
- [ ] [Float64Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array/Float64Array)
- [ ] [Float32Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array/Float32Array)
- [ ] [Uint16Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array/Uint16Array)
- [ ] [Uint32Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array/Uint32Array)
- [ ] [Uint8Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array/Uint8Array)
- [ ] [Uint8ClampedArray constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray/Uint8ClampedArray)
- [ ] [Int16Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array/Int16Array)
- [ ] [Int32Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array/Int32Array)
- [ ] [Int8Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array/Int8Array)
- [ ] [byteOffset](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/byteOffset)
- [ ] [@@iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/@@iterator)
- [ ] [FinalizationRegistry constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/FinalizationRegistry) #2404 
- [ ] [register](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/register) #2404 
- [ ] [unregister](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/unregister) #2404 
- [ ] [next](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/next)
- [ ] [return](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return)
- [ ] [throw](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/throw)
- [ ] [supportedLocalesOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/supportedLocalesOf)
- [ ] [PluralRules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules)
- [ ] [PluralRules constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules)
- [ ] [RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat)
- [ ] [Object constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor)
- [ ] [WeakRef constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef/WeakRef) #2403 
- [ ] [WeakSet constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet/WeakSet)
- [ ] [deref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef/deref) #2403 
- [ ] [await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await)
- [ ] [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)
- [ ] [Array constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Array)

**New examples that require BOB update, so they won't be merged soon:**
- [ ] [canvas](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas)
- [ ] [@font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face)
- [ ] [:target](https://developer.mozilla.org/en-US/docs/Web/CSS/:target)
- [ ] [AsyncFunction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction)
- [ ] [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import)
- [ ] [import.meta](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta)
- [ ] [export](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export)
- [ ] [import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

**Comment by MrBrain295** [comment]
I’ll make an example for `for` but I don’t know what folder to put it in.

**Comment by NiedziolkaMichal** [comment]
[form-attributes](https://github.com/mdn/interactive-examples/tree/main/live-examples/html-examples/form-attributes) should be fine.

**Comment by doanaminh** [comment]
Hey @NiedziolkaMichal! I'd like to work on the CSS example for the overscroll-behavior-x. Which folder should I make the changes in and could you give me an example of what I should be building towards for that page?

**Comment by meghannfh** [comment]
@NiedziolkaMichal Hi, there. I wouldn't mind adding an example for overscroll-behavior-y. If I'm not mistaken, I should be adding my files to the basic-box-model folder, correct?

**Comment by NiedziolkaMichal** [comment]
@doanaminh  @meghannfh `overscroll-behavior-*` properties should be added to `basic-box-model`. Their content and design should be consistent with [overscroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior) property example.
`-block` and `-inline` should show how `writing-mode` and `direction` properties are affecting the behavior of this feature. Take a hint from [border-block](https://developer.mozilla.org/en-US/docs/Web/CSS/border-block).
`-x` and `-y` should show how this feature works only on a single axis.

**Comment by doanaminh** [comment]
Hey @NiedziolkaMichal, I'm working with Yarn and it seems like I can only update the pages once before I am unable to see changes for the day. I'm treating the http://192.168.1.68:9090/ url kind of like a live server to see my changes as I am building out the examples. Is there another way to do see my live changes with all of the needed mdn dependencies or am I doing this wrong? Would love some feedback as it would be my first time contributing for Mozilla; thank you.

**Comment by NiedziolkaMichal** [comment]
@doanaminh Examples are statically generated during build, and after running `start-server` you will only see their compiled version, even after changing source files. You can either use the `build` script again or use `start-watch` which does the same thing automatically after making changes to the files.

**Comment by CBID2** [comment]
Hi @NiedziolkaMichal! I am interested in adding an example to the template pull request.

**Comment by ir3ne** [comment]
Hi @NiedziolkaMichal!, I'd like to work on the JS example starting from `debugger`. Is it good to mention the interest here before to start working on it? Thanks in advance

**Comment by ir3ne** [comment]
@queengooborg since I see you contribute to the guide of contribution for the Javascript Examples is it good to ask you the question above? I hope it is :)

**Comment by bsmth** [comment]
Hi all, thanks a lot for the tracking work and interest in filling in the gaps here. Since all of the infra has been updated and the examples are now maintained in mdn/content, I'm going to close this and we can start a new tracker in the content repo. Thanks a lot!

@ir3ne for the missing examples, we need a new tracking issue in the content repo first to see what's left and what makes sense to add. Are you still interesting in contributing?

**Comment by ir3ne** [comment]
@bsmth sure, I'm still interested!

**Comment by bsmth** [comment]
Super! Maybe a good thing for now is to leave a comment on this Discussion: https://github.com/orgs/mdn/discussions/782

… saying you're interested in adding missing ones and we can keep you in the loop when there's a tracking issue for those. How does that sound?

**Comment by ir3ne** [comment]
@bsmth it sounds good! Done :)
